# Generated by Django 6.0.2 on 2026-03-08 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expos', '0003_expo_platform_commission_percent_expo_stall_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stallbooking',
            unique_together={('expo', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('expo', 'visitor')},
        ),
        migrations.CreateModel(
            name='TicketScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('gate_name', models.CharField(max_length=100)),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expos.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
