# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expos', '0005_theme_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stallbooking',
            unique_together=set(),
        ),
    ]
