# Generated by Django 6.0.2 on 2026-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expos', '0008_ticket_type_and_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='expo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
