# Generated by Django 6.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expos", "0009_expo_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpoReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reminder_type", models.CharField(choices=[("SEVEN_DAYS", "7 days before"), ("ONE_DAY", "1 day before"), ("EVENT_DAY", "Event day")], max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("expo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="expos.expo")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expo_reminders", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("expo", "user", "reminder_type"), name="unique_expo_reminder")],
            },
        ),
    ]
