# Generated by Django 6.0.2 on 2026-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
